project: 
  type: website
  output-dir: docs

website:
  title: "Lipp Lab"
  navbar:
    left:
      - text: "Current Members"
        file: current_members.qmd
      - text: "Alumni"
        file: alumni.qmd
      - text: "Publications"
        file: publications.qmd
      - text: "Current Projects"
        menu:
          - text: "SARS-CoV-2 Wastewater"
            file: projects/covid_wastewater.qmd
    right:
      - icon: github 
        href: https://github.com/lipplab-uga       

format:
  html:
    theme: minty
    highlight: zenburn
    css: styles.css
    toc: FALSE


